jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY')}}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE')}}"
      schema: "{{ env_var('STUDENT_SCHEMA')}}"
      threads: 1
      client_session_keep_alive: False
      query_tag: "{{ env_var('STUDENT_SCHEMA')}}"

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None

    prod:
      type: snowflake
      account: 

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY')}}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE')}}"
      schema: "{{ env_var('STUDENT_SCHEMA')}}_prod"
      threads: 1
      client_session_keep_alive: False
      query_tag: "{{ env_var('STUDENT_SCHEMA')}}_prod"

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None