jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: LYWBBPJ-ODB66944 #"{{ env_var('SNOWFLAKE_ACCOUNT')}}"

      # User/password auth
      user: sandeep90633 #"{{ env_var('SNOWFLAKE_USER')}}"
      private_key: "-----BEGIN ENCRYPTED PRIVATE KEY-----\nMIIFHDBOBgkqhkiG9w0BBQ0wQTApBgkqhkiG9w0BBQwwHAQIBQ0SV5DN8WECAggAMAwGCCqGSIb3DQIJBQAwFAYIKoZIhvcNAwcECCuWYOW75CkaBIIEyNmhFp8hwX3QETHCijSj2BRgJbjy88X4nrFRQH2lKxubMBS5hARWqemEb971KaSSViexAno1c4AMqyGv83sXH+07p6TzqBcWXrvoqTNOedbgPC2PlP55UaVgRYe9TnS7xWTpHkoisTkpAf90qbo5B/uYG+2UO9VG3aKsDumfnFcDHsqEurDlP0bE9AmajjgKVS4RQbep8BWCeyGKWAXZOOb7179I2xNcIaowdA71GRVLemvBBfK6+c9vNzTCMmaubs3sytUrvHWF3aZAwNjDqEA2gwySWMHk8z0XVLWyIKdGZLFhcNwKwsSj8KzCi3Q+/8YW9yC7BIDp2T0HZYdEP+T4lDnifg1+BNoij8QEIy7lUD1IOvMW4jwfBuIiKwd3D7K+7GJCf5EhhiGbXwd+/+RZcQiIuTQFVa87ljMkiHeJsGTCQt/uOo+vfemJol953+llLkLfBwvVAG9YvotF7IfGYhCRpe/t88aYV/1Vu3dUeb4bNi/2LqQ2PUpb9qzjahUpKiSNY0wzJNGsSJMaQcskcVmH3QSzc6l1ja2cszkgSrFolCtVOr94vk240PhNfcSPEem5Y8DYTqVi8I/67MnjdM3ouXw8zkOnvbYcgTisZJN7jFjDpXniDND25heeIdSJAviinlA/HC19HhGkFyqTRYfpJbzKecUChmse5ZV4iFWOe/CDN0PxP2A1RFW1Dv7sBAVTvaUFRz44q6ouIDbq0w3NG8cVFvHErbfjYKWDOwuzip3TnsLz1JibNzVyKQa87xDkpoucJ83m+sDyNRZMbZWGPtHlWEX7UiK3yBwqZgyfIc1SDheVR65dJy2OBZQcR7X/sN6xdODHug4GwuTY7eJ/aWS+lHOaud51GniBZtdwETqCarryYirPG/AWiCITtMn/zWc5DmhBtwO19MT3IVtYSTHHt2pNY0/F9q3wFM4nAe1W7KZt3BNvyZiNV+VZhSU0FItQfwHf9QZvNOgoz6mTjfVthxRLHPBTtz22fMhPZDe8IRaKkxUkpQnMDSGiOFkR98ITkZWC97Fdo1U25FDvpZfencusurxMrqTDDJEhHSBTI7Iz6gFdALwh5Yr5HmWvEagHlgOmD97l7J1U51Go/sUP/AtMMXDa8spvr7DszwuVSmHvEORDZx4t9PRDH0rBEaIDkpA0tiaurNXbR17X3D+dbWPehj6JxB/hqFgNwpj3czqqBBcBXgzr5YrGYp6cwkne07+mCCfJ6qNEGB3Xgs9+xjPL2k/W9apo3HtKM1VUKNQUfJputMKQuIganVOR0k6ut0b69GfXXad2zImMUUA6eQpaXcRgy69Iw+tGX0HA+3cGvylkNpTYI66qE0uzp1aFF99mjY9thyYDm3+NNlw8pZU1Bo5Gg6O/aTZaTVnKd/quDDscR+zofNEhrUgdiGJIi8DeLPk3BdA5lc1/vG/RdzxxHbepYhPUgfiMHE5Dk0G1rxmVf6a/j2/a/6N+wR4SmWAlxtGJNfTtFLHe5kinFgLrN0Gte7kCD9NcQlYwZkjabPFT7m0dd9hYq34OnhY3ytdIwx1HzQZtFeHq5Ni3Xyaj6h3iapAUj36Bi5xp3gxBOLZeHYrF/2NnnxRFb2q2rmqpE/N8lzcfOEgE7Ra7Zw==\n-----END ENCRYPTED PRIVATE KEY-----" #"{{ env_var('SNOWFLAKE_PRIVATE_KEY')}}"
      private_key_passphrase: "8776" #"{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE')}}"
      role: all_users_role #"{{ env_var('SNOWFLAKE_ROLE')}}"
      database: dataexpert_student # "{{ env_var('SNOWFLAKE_DATABASE')}}"
      warehouse: COMPUTE_WH #  "{{ env_var('SNOWFLAKE_WAREHOUSE')}}"
      schema: sandeep90633 # "{{ env_var('STUDENT_SCHEMA')}}"
      threads: 1
      client_session_keep_alive: False
      query_tag: sandeep90633 # "{{ env_var('STUDENT_SCHEMA')}}"

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT')}}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY')}}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE')}}"
      schema: "{{ env_var('STUDENT_SCHEMA')}}_prod"
      threads: 1
      client_session_keep_alive: False
      query_tag: "{{ env_var('STUDENT_SCHEMA')}}_prod"

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None